[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug", "-lxcm=trace" ]
chain = "polkadot-local"
chain_spec_command = "./bin/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9900
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "dave"
    validator = true
    args = ["--state-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1000
chain = "asset-hub-polkadot-local"
chain_spec_command = "./bin/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9910
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0" ]

    [[parachains.collators]]
    name = "collator2"
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

[[parachains]]
id = 2000
chain = "local-v"
cumulus_based = true

    [[parachains.collators]]
    name = "collator3"
    ws_port = 9920
    command = "./target/release/mythical-node"
    args = [ "-lxcm=trace", "--state-cache-size=0"]

    [[parachains.collators]]
    name = "collator4"
    command = "./target/release/mythical-node"
    args = [ "-lxcm=trace", "--state-cache-size=0"]