[relaychain]
chain = "paseo-local"
default_command = "./bin/polkadot"
chain_spec_command = "./bin/paseo-chain-spec-generator {% raw %} {{chainName}} {% endraw %}"

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
scheduling_lookahead = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2


	[[relaychain.nodes]]
	name = "alice"
	validator = true

	[[relaychain.nodes]]
	name = "bob"
	validator = true

[[parachains]]
id = 3369
addToGenesis = true
cumulus_based = true
chain = "local-v"

	[[parachains.collators]]
	name = "muse-collator01"
	command = "./target/release/mythos-node"
	ws_port = 9933
	rpc_port = 8833
	args = ["--pool-limit 500000 --pool-kbytes 2048000 --rpc-max-connections 10000 -lparachain=debug"]

	[[parachains.collators]]
	name = "muse-collator02"
	ws_port = 9822
	rpc_port = 8822
	command = "./target/release/mythos-node"
	args = ["--rpc-max-connections 10000"]
