name: Build, test and lint

on:
  push:
    branches:
      - release-**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: "Build"
    runs-on: arc-runners-project-mythical
    container:
      image: "paritytech/ci-unified:bullseye-1.75.0-2024-01-22-v20240222"
    steps:
      - uses: actions/checkout@v3

      - name: Rustfmt
        run: |
          cargo fmt --all --check

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.0
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Check Build
        run: |
          cargo check --release --features try-runtime,runtime-benchmarks

      - name: Run tests
        run: cargo test --release --features try-runtime,runtime-benchmarks --locked --verbose --all
